
// Immutable record of a balance change
export interface LedgerEntry {
    // Unique ID for this entry (e.g. autogenerated or composite)
    ledgerEntryId: string;

    // The transaction that caused this entry
    transactionId: string;

    // The wallet this entry belongs to
    walletId: string;

    // Direction of money flow relative to the wallet
    direction: 'DEBIT' | 'CREDIT';

    // Amount (always positive)
    amount: number;

    // Currency code (e.g. 'USD')
    currency: string;

    // Optional: The balance of the wallet *after* this entry was applied.
    // Useful for quick recon, but not the source of truth for the balance itself.
    balanceSnapshot?: number;

    // Timestamp when this entry was strictly created
    occurredAt: string; // ISO 8601
}
