// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdQYhDGjjQbddBx8ixCofyeCVUcnGJ6Sg',
    appId: '1:778167433894:web:8a0e61f1a33d4f59ad5267',
    messagingSenderId: '778167433894',
    projectId: 'boklo-wallet',
    authDomain: 'boklo-wallet.firebaseapp.com',
    storageBucket: 'boklo-wallet.firebasestorage.app',
    measurementId: 'G-JDWHMK9F4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVAHn8COd9QE3_vHs7aCzadv3Y6cPFQyM',
    appId: '1:778167433894:android:9f65454df2a5faebad5267',
    messagingSenderId: '778167433894',
    projectId: 'boklo-wallet',
    storageBucket: 'boklo-wallet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVIAbYfwl0YhPnCyJH3rIgzxqSwx9sUk4',
    appId: '1:778167433894:ios:9261b9c8718a3ef8ad5267',
    messagingSenderId: '778167433894',
    projectId: 'boklo-wallet',
    storageBucket: 'boklo-wallet.firebasestorage.app',
    iosBundleId: 'com.boklo.wallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdQYhDGjjQbddBx8ixCofyeCVUcnGJ6Sg',
    appId: '1:778167433894:web:89d41bea7e02be20ad5267',
    messagingSenderId: '778167433894',
    projectId: 'boklo-wallet',
    authDomain: 'boklo-wallet.firebaseapp.com',
    storageBucket: 'boklo-wallet.firebasestorage.app',
    measurementId: 'G-HKGL58N1JT',
  );
}
